package webapp;

import java.util.Date;

/**
 * A class for representing the association between one persons and one service, with two ids (person, service), a description,
 * a creation date, a limit Date and a status(request,offer).
 * @author Emiliano Castillo and Julien Foucault, Universit&eacute; de Caen Basse-Normandie, France
 * @since January, 2016
 */
public class PersonServiceAssociation {

	/** The association's idPerson*/
	private int idPerson;
	
	/** The association's idService*/
	private int idService;
	
	/** The association's description*/
	private String description;
	
	/** The association's creation Date*/
	private Date creationDate;
	
	/** The association's limitDate*/
	private Date limitDate;
	
	/** The association's status*/
	private int status;
	
	/**
	 *  Builds a new association Person - Service.
	 * @param idPerson The person's id
	 * @param idService The service's id
	 * @param description The association's description
	 * @param creationDate The assocition's creation date
	 * @param limitDate The association's limit date
	 * @param status The association's status
	 */
	public PersonServiceAssociation(int idPerson, int idService, String description, Date creationDate, Date limitDate, int status) {
		this.idPerson = idPerson;
		this.idService = idService;
		this.description = description;
		this.creationDate = creationDate;
		this.limitDate = limitDate;
		this.status = status;
	}
	/**
	 *  Builds a new association Person - Service with the creation date autogenerated.
	 * @param idPerson The person's id
	 * @param idService The service's id
	 * @param description The association's description
	 * @param limitDate The association's limit date
	 * @param status The association's status
	 */
	public PersonServiceAssociation(int idPerson, int idService, String description, Date limitDate, int status) {
		this(idPerson, idService, description, new Date(), limitDate, status);
	}
	/**
	 * Returns the person's id.
	 * @return The person's id
	 */
	public int getIdPerson() {
		return idPerson;
	}
	/**
	 * Returns the service id.
	 * @return The service id
	 */
	public int getIdService() {
		return idService;
	}
	/**
	 * Returns the association's description.
	 * @return The association's description
	 */
	public String getDescription() {
		return description;
	}
	/**
	 * Returns the association's creation date.
	 * @return The association's creation date
	 */
	public Date getCreationDate() {
		return creationDate;
	}
	/**
	 * Returns the association's limit date.
	 * @return The association's limit date
	 */
	public Date getLimitDate() {
		return limitDate;
	}
	/**
	 * Returns the association's status.
	 * @return The association's status
	 */
	public int getStatus() {
		return status;
	}
	
}
